server:
  port: 8083
  servlet:
    context-path: /api/usecaseui-intent-analysis/v1
spring:
  application:
    name: uui-intent-analysis
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_IP:127.0.0.1}:${POSTGRES_PORT:5432}/${POSTGRES_DB_NAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      schema-locations: classpath*:intent-analysis-init.sql
      data-locations: classpath*:intent-analysis-data.sql
      mode: always
mybatis:
  configuration:
    database-id: PostgreSQL
  mapper-locations: classpath*:mybatis/sql/*.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: ${TRACING_ENABLED:true}
    sampling:
      probability: 1.0 # sample every request
  zipkin:
    tracing:
      endpoint: http://${COLLECTOR_HOST:jaeger-collector.istio-system}:${COLLECTOR_PORT:9411}/api/v2/spans

rest:
  policy:
    username: policyadmin
    password: zb!XztG34
  so:
    username: InfraPortalClient
    password: password1$
  aai:
    username: AAI
    password: AAI
